/*
 * Gates API
 *
 * OpenAPI specification for the Gates API
 *
 * The version of the OpenAPI document: 1.12.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// ApiInfo : Contains information about the API such as name and version.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiInfo {
    /// The name of the API.
    #[serde(rename = "name")]
    pub name: String,
    /// The version of the API.
    #[serde(rename = "version")]
    pub version: String,
}

impl ApiInfo {
    /// Contains information about the API such as name and version.
    pub fn new(name: String, version: String) -> ApiInfo {
        ApiInfo {
            name,
            version,
        }
    }
}

