/*
 * Gates API
 *
 * OpenAPI specification for the Gates API
 *
 * The version of the OpenAPI document: 1.12.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// Comment : Comments will help you identify the reasons for the gate.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Comment {
    /// Identifies the comment.
    #[serde(rename = "id")]
    pub id: String,
    /// Very important text to show why you did it.
    #[serde(rename = "message")]
    pub message: String,
    /// The exact moment the comment was created.
    #[serde(rename = "created")]
    pub created: String,
}

impl Comment {
    /// Comments will help you identify the reasons for the gate.
    pub fn new(id: String, message: String, created: String) -> Comment {
        Comment {
            id,
            message,
            created,
        }
    }
}

