/*
 * Gates API
 *
 * OpenAPI specification for the Gates API
 *
 * The version of the OpenAPI document: 1.12.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateGateRequest {
    /// You can use this as a category to group your gates.
    #[serde(rename = "group")]
    pub group: String,
    /// This is another deeper nesting level to group your gates.
    #[serde(rename = "service")]
    pub service: String,
    /// Identifies a gate for group and service. This is the third level of nesting.
    #[serde(rename = "environment")]
    pub environment: String,
    /// Specifies a way to order the gate for frontend display purpose.
    #[serde(rename = "display_order", skip_serializing_if = "Option::is_none")]
    pub display_order: Option<f64>,
}

impl CreateGateRequest {
    pub fn new(group: String, service: String, environment: String) -> CreateGateRequest {
        CreateGateRequest {
            group,
            service,
            environment,
            display_order: None,
        }
    }
}

