/*
 * Gates API
 *
 * OpenAPI specification for the Gates API
 *
 * The version of the OpenAPI document: 1.12.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// GateState : This can only be open or closed.
/// This can only be open or closed.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GateState {
    #[serde(rename = "open")]
    Open,
    #[serde(rename = "closed")]
    Closed,

}

impl ToString for GateState {
    fn to_string(&self) -> String {
        match self {
            Self::Open => String::from("open"),
            Self::Closed => String::from("closed"),
        }
    }
}

impl Default for GateState {
    fn default() -> GateState {
        Self::Open
    }
}

