/*
 * Gates API
 *
 * OpenAPI specification for the Gates API
 *
 * The version of the OpenAPI document: 1.12.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// GateStateRep : Wrapper object for the state of a gate.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GateStateRep {
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<models::GateState>,
}

impl GateStateRep {
    /// Wrapper object for the state of a gate.
    pub fn new() -> GateStateRep {
        GateStateRep {
            state: None,
        }
    }
}

