/*
 * Gates API
 *
 * OpenAPI specification for the Gates API
 *
 * The version of the OpenAPI document: 1.12.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateGateStateRequest {
    #[serde(rename = "state")]
    pub state: models::GateState,
}

impl UpdateGateStateRequest {
    pub fn new(state: models::GateState) -> UpdateGateStateRequest {
        UpdateGateStateRequest {
            state,
        }
    }
}

