/*
 * Gates API
 *
 * OpenAPI specification for the Gates API
 *
 * The version of the OpenAPI document: 1.12.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateDisplayOrderRequest {
    /// Is expected to be a positive number, but can basically be anything.
    #[serde(rename = "display_order")]
    pub display_order: f64,
}

impl UpdateDisplayOrderRequest {
    pub fn new(display_order: f64) -> UpdateDisplayOrderRequest {
        UpdateDisplayOrderRequest {
            display_order,
        }
    }
}

