name: ci
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ui:
    uses: ./.github/workflows/ui.yaml

  api:
    uses: ./.github/workflows/api.yaml

  openapi:
    uses: ./.github/workflows/openapi.yaml
