name: ui
on:
  workflow_call:

jobs:
  lint-check-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          cache-dependency-path: ui
      - uses: SpicyPizza/create-envfile@v2
        with:
          directory: ui
          envkey_PUBLIC_API_BASE_URL: http://localhost:9000/api
      - run: npm ci
        working-directory: ui
      - run: npm run lint
        working-directory: ui
      - run: npm run check
        working-directory: ui
      - run: npm run test:unit
        working-directory: ui
      - run: npm run test:integration
        working-directory: ui
