on:
  workflow_call:

jobs:
  lint-check-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - run: npm ci
        working-directory: ui
      - run: npm run lint
      - run: npm run check
      - run: npm run test:unit
      - run: npm run test:integration
